"""
storage.py — CSV-based conversation persistence.

Saves logs to  <project_root>/data/conversation_log.csv
The project root is determined as the directory containing this file's
parent package, so the path is correct regardless of where you launch
main.py from.
"""

import os
import pandas as pd
from datetime import datetime

# Resolve data/ relative to the project root (parent of the `agent` package)
_HERE       = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_HERE)
DATA_DIR    = os.path.join(_PROJECT_ROOT, "data")
LOG_PATH    = os.path.join(DATA_DIR, "conversation_log.csv")

_COLUMNS = ["timestamp", "user_text", "ai_response", "intent",
            "emails", "phones", "dates", "keywords"]


def _ensure_dir() -> None:
    os.makedirs(DATA_DIR, exist_ok=True)


def log_conversation(
    user_text: str,
    ai_response: str,
    intent: str,
    entities: dict | None = None,
) -> None:
    """
    Append one conversation turn to the CSV log.

    Parameters
    ----------
    user_text   : Raw transcript from the user.
    ai_response : Response generated by the assistant.
    intent      : Detected intent label.
    entities    : Dict returned by extract_entities() (optional).
    """
    _ensure_dir()

    entities = entities or {}
    row = {
        "timestamp":   datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "user_text":   user_text,
        "ai_response": ai_response,
        "intent":      intent,
        # Store list fields as pipe-separated strings for CSV readability
        "emails":      " | ".join(entities.get("emails",   [])),
        "phones":      " | ".join(entities.get("phones",   [])),
        "dates":       " | ".join(entities.get("dates",    [])),
        "keywords":    " | ".join(entities.get("keywords", [])),
    }

    df = pd.DataFrame([row], columns=_COLUMNS)

    if not os.path.exists(LOG_PATH):
        df.to_csv(LOG_PATH, index=False)
    else:
        df.to_csv(LOG_PATH, mode="a", header=False, index=False)

    print(f"[Storage] Logged to {LOG_PATH}")


def read_log() -> pd.DataFrame:
    """
    Return the full conversation log as a DataFrame.
    Returns an empty DataFrame if no log exists yet.
    """
    _ensure_dir()
    if not os.path.exists(LOG_PATH):
        return pd.DataFrame(columns=_COLUMNS)
    return pd.read_csv(LOG_PATH)


def get_recent(n: int = 5) -> pd.DataFrame:
    """Return the *n* most recent conversation entries."""
    df = read_log()
    return df.tail(n).reset_index(drop=True)


def search_log(keyword: str) -> pd.DataFrame:
    """Return all rows where user_text or ai_response contains *keyword*."""
    df = read_log()
    if df.empty:
        return df
    mask = (
        df["user_text"].str.contains(keyword, case=False, na=False)
        | df["ai_response"].str.contains(keyword, case=False, na=False)
    )
    return df[mask].reset_index(drop=True)
